language: dart
dist: trusty
sudo: false
dart: dev
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - cd package/butterfly
  - pub get
  - dart -c test/butterfly_test.dart
  - dartfmt -n --set-exit-if-changed lib/ test/ bin/
  - dartanalyzer --strong --fatal-warnings lib/ test/
cache:
  directories:
    - $HOME/.pub-cache
