name: angular_interop
description: A hello world app
dependencies:
  angular: '^4.0.0'
  angular_components:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  butterfly_components:
    path: '../../package/butterfly_components'
  butterfly:
    path: ../../package/butterfly

transformers:
- $dart2js:
    minify: false
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc