name: angular_interop
description: A hello world app
dependencies:
  angular: '5.0.0-alpha'
  butterfly_components:
    path: '../../package/butterfly_components'
  butterfly:
    path: ../../package/butterfly
  dart_to_js_script_rewriter:

transformers:
- dart_to_js_script_rewriter
- angular:
    entry_points: web/main.dart

web:
  compiler:
    debug: dartdevc