name: butterfly
version: 0.0.2
authors:
- Yegor Jbanov <yjbanov@google.com>
description: >
  A web framework for Dart based on Flutter's widget model. The goal of the
  project is conceptual and data model compatibility with Flutter. An explicit
  non-goal is "write once, run anywhere".
homepage: https://github.com/yjbanov/butterfly
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  path:
  meta:
  mime:
  logging:
  ansicolor:
  watcher: ^0.9.7+3
  vm_service_lib:
dev_dependencies:
  test: '>=1.3.3 <2.0.0'
  charcode:
  quiver:
